; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
libdeps_dir  = .piolibdeps

[env:KillDozer2]
lib_deps =
         https://github.com/stevemarple/AsyncDelay/archive/refs/heads/master.zip
         https://github.com/Bodmer/TFT_eSPI/archive/refs/heads/master.zip
         https://github.com/Sebagabones/Catppuccin_TFT_eSPI/archive/refs/heads/main.zip
         https://bitbucket.org/teckel12/arduino-new-ping/downloads/NewPing_v1.9.7.zip
build_flags =
  -D USER_SETUP_LOADED=1                        ; this is so we don't need to change any of the libary files for tft_espi.h
  -include $PROJECT_LIBDEPS_DIR/$PIOENV/TFT_eSPI/User_Setups/Setup206_LilyGo_T_Display_S3.h

platform = espressif32
board = lilygo-t-display-s3
framework = arduino

upload_speed = 115200

board_build.mcu = esp32s3

board_build.f_cpu = 240000000L

debug_tool = esp-builtin
upload_protocol = esptool       ;this may cause issues for some of you - if it does, let everyone know and change it to match your normal platformio.ini file

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
extra_scripts = pre:extra_script.py
